#!/usr/bin/perl
#
# UPower Script
# Copyright 2017-19 Jishnu Mohan <jishnu7@gmail.com>
#
# Original ACPI Script by
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $icon;
my $color;
my $timeleft;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

open (ACPI, "upower --show-info /org/freedesktop/UPower/devices/battery_BAT$bat_number | egrep 'state|percentage|time to empty|time to full' | xargs |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /state: (\w+) time to (\w+): (\d+.\d+ \w+) percentage: (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$timeleft = $3;
$percent = $4;

if ($percent < 10) {
	$icon = "";
  $color = "#FF0000";
} elsif ($percent < 20) {
	$icon = "";
  $color = "#FFAE00";
} elsif ($percent < 30) {
	$icon = "";
  $color = "#FFF600";
} elsif ($percent < 40) {
	$icon = "";
  $color = "#FFF600";
} elsif ($percent < 50) {
	$icon = "";
  $color = "#FFF600";
} elsif ($percent < 60) {
	$icon = "";
  $color = "#A8FF00";
} elsif ($percent < 70) {
	$icon = "";
  $color = "#A8FF00";
} elsif ($percent < 80) {
	$icon = "";
  $color = "#A8FF00";
} elsif ($percent < 90) {
	$icon = "";
  $color = "#A8FF00";
} else {
	$icon = "";
  $color = "#A8FF00";
}

if ($status eq 'charging') {
	$icon = '';
} elsif ($status eq 'fully-charged') {
	$icon = '';
}

$full_text = "$percent% $timeleft";

$short_text = $full_text;

# to print utf-8
use open ':std', ':encoding(UTF-8)';

print "$icon $full_text\n";
print "$short_text\n";
print "$color\n";

exit(0);
