DOTFILES_GIT=$HOME/git/dotfiles

# Path to oh-my-zsh configuration.
ZSH=$DOTFILES_GIT/zsh/oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="agnoster"

DEFAULT_USER="jishnu"

plugins=(git archlinux systemd sublime urltools zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# custom alias, exports, functions
source $DOTFILES_GIT/aliases
source $DOTFILES_GIT/secrets
source $DOTFILES_GIT/exports
source $DOTFILES_GIT/functions
if [[ -s '/etc/zsh_command_not_found' ]];
then
    source /etc/zsh_command_not_found
else
    if [[ -s '/usr/share/doc/pkgfile/command-not-found.zsh' ]];
    then
        source /usr/share/doc/pkgfile/command-not-found.zsh
    fi
fi

DISABLE_LS_COLORS=true

unsetopt correct_all

# auto rehash commands
zstyle ':completion:*' rehash true

# Home, Insert key fix for urxvt
bindkey "^[[7~" beginning-of-line
bindkey "^[[8~" end-of-line

precmd () (
    echo -ne '\a'
)
