DOTFILES_GIT=$HOME/git/dotfiles

# Path to oh-my-zsh configuration.
ZSH=$DOTFILES_GIT/zsh/oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="agnoster"

DEFAULT_USER="jishnu"

plugins=(git archlinux systemd sublime urltools zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# alias
source $DOTFILES_GIT/aliases
source $DOTFILES_GIT/ssh
source $DOTFILES_GIT/exports
source $DOTFILES_GIT/functions

DISABLE_LS_COLORS=true

unsetopt correct_all

# auto rehash commands
zstyle ':completion:*' rehash true

# Home, Insert key fix for urxvt
bindkey "^[[7~" beginning-of-line
bindkey "^[[8~" end-of-line

precmd () (
    echo -ne '\a'
)
