# Enable Powerlevel11k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

DOTFILES_GIT=$HOME/git/dotfiles

# Path to oh-my-zsh configuration.
ZSH=$DOTFILES_GIT/zsh/oh-my-zsh

# Set name of the theme to load.
#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel10k/powerlevel10k"

DEFAULT_USER="jishnu"
DISABLE_AUTO_TITLE="true"

# Arch
#plugins=(git archlinux systemd urltools zsh-syntax-highlighting command-not-found history-substring-search web-search zsh-autosuggestions)
# MacOS
plugins=(git urltools zsh-syntax-highlighting command-not-found history-substring-search zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# custom alias, exports, functions
source $DOTFILES_GIT/aliases
source $DOTFILES_GIT/secrets
source $DOTFILES_GIT/exports
source $DOTFILES_GIT/functions
source $DOTFILES_GIT/directories
test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)

autoload -U zmv

DISABLE_LS_COLORS=true

unsetopt correct_all

# auto rehash commands
zstyle ':completion:*' rehash true

# Home, Insert key fix for urxvt
bindkey "^[[7~" beginning-of-line
bindkey "^[[8~" end-of-line

precmd () (
    echo -ne '\a'
)

# greeter with disk usage and uptime info
#if [ -f $DOTFILES_GIT/zsh/bash_greeter.sh ]; then
#    . $DOTFILES_GIT/zsh/bash_greeter.sh
#fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# fnm
export PATH=/home/jishnu/.fnm:$PATH
eval "`fnm env --use-on-cd`"
